header: "§ePowerNukkitX Server"
lines:
  - ""
  - "§7Welcome %player_displayname%"
  - "§5%player_pos%"
  - "§7Your money: §q%money%" #Requires LLamaEconomy
  - ""
  - "§7Your ping: §v%player_ping%ms"
  - "§7Online: §t%server_online% / %server_max_players%"
  - ""
  - "§b%server_motd%"
  - "§eThank you for using PNX"